disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 120
  error: 150

included:
  - Fasted
  - Shared
  - FastedTests
  - FastedUITests
  - FastedWidgets
  - FastedWatch
  - FastedWatchWidgets


excluded:
  - Fasted.xcodeproj
  - DerivedData
  - build
