default_platform(:ios)

platform :ios do
  desc "Run full test suite (Unit & UI tests)"
  lane :test do
    run_tests(
      project: "Fasted.xcodeproj",
      scheme: "FastedTests",
      devices: ["iPhone 17 Pro"],
      clean: true
    )
  end

  desc "Capture production App Store screenshots"
  lane :screenshots do
    sh("../scripts/generate_screenshots.sh 'iPhone 17 Pro'")
  end

  desc "Build and upload to TestFlight (Beta)"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: true
    )

    team_id = ENV["APPLE_TEAM_ID"]

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.grusy.Fasted",
      team_id: team_id
    )

    build_app(
      project: "Fasted.xcodeproj",
      scheme: "Fasted",
      clean: true,
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates -allowProvisioningDeviceRegistration DEVELOPMENT_TEAM=#{team_id}",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload metadata, screenshots, and submit build to App Store for review"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: true
    )

    team_id = ENV["APPLE_TEAM_ID"]

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.grusy.Fasted",
      team_id: team_id
    )

    build_app(
      project: "Fasted.xcodeproj",
      scheme: "Fasted",
      clean: true,
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates -allowProvisioningDeviceRegistration DEVELOPMENT_TEAM=#{team_id}",
      export_xcargs: "-allowProvisioningUpdates"
    )

    deliver(
      api_key: api_key,
      force: true,
      screenshots_path: "./AppStoreScreenshots",
      metadata_path: "./fastlane/metadata",
      skip_metadata: false,
      skip_screenshots: false,
      submit_for_review: true,
      automatic_release: true
    )
  end
end
