// Generated by scripts/resolve_version.sh - DO NOT EDIT DIRECTLY
import Foundation

public enum BuildMetadata {
    public static let marketingVersion = "1.1.55"
    public static let prNumber: Int? = 55
    public static let gitCommit = "484436d"
    public static let buildDate = "2026-09-20"
}
