#!/usr/bin/env bash
set -euo pipefail

# scripts/resolve_version.sh
# Resolves marketing version and build metadata for CI, Fastlane, and Xcode builds.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

VERSION_FILE="$REPO_ROOT/VERSION"
if [ -f "$VERSION_FILE" ]; then
    BASE_VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
else
    BASE_VERSION="1.1.0"
fi

# Split BASE_VERSION into major and minor (e.g. 1.1.0 -> 1.1)
IFS='.' read -r BASE_MAJOR BASE_MINOR BASE_PATCH <<< "$BASE_VERSION"
BASE_MAJOR="${BASE_MAJOR:-1}"
BASE_MINOR="${BASE_MINOR:-1}"

RESOLVED_VERSION=""
PR_NUMBER=""

# 1. Explicit override via environment
if [ -n "${VERSION_OVERRIDE:-}" ]; then
    RESOLVED_VERSION="$VERSION_OVERRIDE"
elif [ -n "${MARKETING_VERSION:-}" ] && [ "$MARKETING_VERSION" != "1.1" ] && [ "$MARKETING_VERSION" != "1.1.0" ]; then
    RESOLVED_VERSION="$MARKETING_VERSION"
# 2. Release tag (e.g. refs/tags/v1.2.0 -> 1.2.0)
elif [[ "${GITHUB_REF:-}" == refs/tags/v* ]]; then
    RESOLVED_VERSION="${GITHUB_REF#refs/tags/v}"
elif [[ "${GITHUB_REF:-}" == refs/tags/* ]]; then
    RESOLVED_VERSION="${GITHUB_REF#refs/tags/}"
# 3. GitHub Actions Pull Request event payload
elif [ -n "${GITHUB_EVENT_PATH:-}" ] && [ -f "${GITHUB_EVENT_PATH:-}" ]; then
    DETECTED_PR="$(grep -m 1 '"number":' "$GITHUB_EVENT_PATH" 2>/dev/null | awk -F: '{print $2}' | tr -d ' ,' || true)"
    if [ -n "$DETECTED_PR" ] && [[ "$DETECTED_PR" =~ ^[0-9]+$ ]]; then
        PR_NUMBER="$DETECTED_PR"
        RESOLVED_VERSION="${BASE_MAJOR}.${BASE_MINOR}.${PR_NUMBER}"
    fi
fi

# 4. GitHub Actions ref for PR (refs/pull/<PR>/merge)
if [ -z "$RESOLVED_VERSION" ] && [[ "${GITHUB_REF:-}" =~ ^refs/pull/([0-9]+)/ ]]; then
    PR_NUMBER="${BASH_REMATCH[1]}"
    RESOLVED_VERSION="${BASE_MAJOR}.${BASE_MINOR}.${PR_NUMBER}"
fi

# 5. Git commit message check (e.g. Merge pull request #55 ... or (#55))
if [ -z "$RESOLVED_VERSION" ]; then
    LAST_PR_COMMIT="$(git log -E --grep="(Merge pull request #|\(#[0-9]+\))" -n 1 --pretty=%s 2>/dev/null || true)"
    if [ -n "$LAST_PR_COMMIT" ]; then
        DETECTED_PR="$(echo "$LAST_PR_COMMIT" | sed -E 's/.*(Merge pull request #|\(#)([0-9]+).*/\2/' || true)"
        if [ -n "$DETECTED_PR" ] && [[ "$DETECTED_PR" =~ ^[0-9]+$ ]]; then
            PR_NUMBER="$DETECTED_PR"
            RESOLVED_VERSION="${BASE_MAJOR}.${BASE_MINOR}.${PR_NUMBER}"
        fi
    fi
fi

# 6. Branch name check (e.g. pr-55, issue-55)
if [ -z "$RESOLVED_VERSION" ]; then
    CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
    if [[ "$CURRENT_BRANCH" =~ (pr|pull|issue)[/-]?([0-9]+) ]]; then
        PR_NUMBER="${BASH_REMATCH[2]}"
        RESOLVED_VERSION="${BASE_MAJOR}.${BASE_MINOR}.${PR_NUMBER}"
    fi
fi

# 7. Fallback: commit count since repository inception
if [ -z "$RESOLVED_VERSION" ]; then
    COMMIT_COUNT="$(git rev-list --count HEAD 2>/dev/null || echo 0)"
    RESOLVED_VERSION="${BASE_MAJOR}.${BASE_MINOR}.${COMMIT_COUNT}"
fi

# Git commit SHA and build date
GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
BUILD_DATE="$(date -u +"%Y-%m-%d")"

# Update project.yml MARKETING_VERSION if present
PROJECT_YML="$REPO_ROOT/project.yml"
if [ -f "$PROJECT_YML" ]; then
    sed -i '' -E "s/MARKETING_VERSION: .*/MARKETING_VERSION: \"$RESOLVED_VERSION\"/" "$PROJECT_YML"
fi

# Generate Shared/BuildMetadata.swift
METADATA_FILE="$REPO_ROOT/Shared/BuildMetadata.swift"
mkdir -p "$(dirname "$METADATA_FILE")"

cat << SWIFT > "$METADATA_FILE"
// Generated by scripts/resolve_version.sh - DO NOT EDIT DIRECTLY
import Foundation

public enum BuildMetadata {
    public static let marketingVersion = "$RESOLVED_VERSION"
    public static let prNumber: Int? = ${PR_NUMBER:-nil}
    public static let gitCommit = "$GIT_COMMIT"
    public static let buildDate = "$BUILD_DATE"
}
SWIFT

# Export for GitHub Actions
if [ -n "${GITHUB_ENV:-}" ] && [ -f "${GITHUB_ENV:-}" ]; then
    echo "MARKETING_VERSION=$RESOLVED_VERSION" >> "$GITHUB_ENV"
    echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
    echo "GIT_COMMIT=$GIT_COMMIT" >> "$GITHUB_ENV"
fi

if [ -n "${GITHUB_OUTPUT:-}" ] && [ -f "${GITHUB_OUTPUT:-}" ]; then
    echo "marketing_version=$RESOLVED_VERSION" >> "$GITHUB_OUTPUT"
    echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
    echo "git_commit=$GIT_COMMIT" >> "$GITHUB_OUTPUT"
fi

echo "Resolved Version: $RESOLVED_VERSION (PR: ${PR_NUMBER:-none}, Commit: $GIT_COMMIT, Date: $BUILD_DATE)"
echo "MARKETING_VERSION=$RESOLVED_VERSION"
